version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\Build.ps1
test: off
artifacts:
- path: .\artifacts\win10-x64
  name: DbfBulkCopy-win10-x64
- path: .\artifacts\osx.10.10-x64
  name: DbfBulkCopy-osx.10.10-x64
- path: .\artifacts\ubuntu.14.04-x64
  name: DbfBulkCopy-ubuntu.14.04-x64
deploy:
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: zIuIoM6+3Bc95kSVegG4Lwls01vu+J5OlwOFG2CSaB2YLNdYsTtNqJVnWrnIXMBl
  artifact: artifacts\DbfBulkCopy-win10-x64.zip,artifacts\DbfBulkCopy-osx.10.10-x64.zip,artifacts\DbfBulkCopy-ubuntu.14.04-x64.zip
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true