version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\Build.ps1
test: off
artifacts:
- path: .\artifacts\win10-x64
  name: win10-x64
- path: .\artifacts\osx.10.10-x64
  name: osx.10.10-x64
- path: .\artifacts\ubuntu.14.04-x64
  name: ubuntu.14.04-x64
deploy:
  release: DbfBulkCopy-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: <your encrypted token> # your encrypted token from GitHub
  artifact: .\artifacts\win10-x64.zip,.\artifacts\osx.10.10-x64.zip,.\artifacts\ubuntu.14.04-x64.zip
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only